ClassLibrary/ClassLibrary.csproj, ClassLibrary/clsGame.cs, Testing2/TestingProduct.csproj, Testing2/tstGame.cs
=> Added testing for Product or Game class

.editorconfig, ClassLibrary/ClassLibrary.csproj, ClassLibrary/clsOrder.cs, Testing3/TestingOrder.csproj, Testing3/tstOrder.cs
=> Added testing for Order Class

ClassLibrary/clsCustomer.cs, Testing4/tstCustomer.cs
Added Testing to customer class
=> Added Testing to customer class

ClassLibrary/clsGame.cs, Testing2/tstGame.cs
=> Added testing for game class

ClassLibrary/clsOrder.cs, Testing3/tstOrder.cs
=> added testing in order class

AdminSystem/ProductDataEntry.aspx, AdminSystem/ProductDataEntry.aspx.cs, AdminSystem/ProductViewer.aspx.cs, Skeleton.sln
=> Adding a Simple Presentation Layer in product session

ClassLibrary/clsOrder.cs, Testing3/tstOrder.cs
=> completed testing for order class

ClassLibrary/ClassLibrary.csproj, ClassLibrary/clsStaff.cs, Testing1/TestingStaff.csproj, Testing1/tstStaff.cs
=> add testing to staff class

AdminSystem/ProductDataEntry.aspx.cs, AdminSystem/ProductViewer.aspx.cs
=> Adding a Simple Presentation Layer in product session(Final)

ClassLibrary/clsGame.cs, Testing2/tstGame.cs
This code works fine but need to add more test methods later.
=> Creating the Find Method in product session(unfinished)

AdminSystem/OrderDataEntry.aspx, AdminSystem/OrderDataEntry.aspx.cs, AdminSystem/OrderViewer.aspx, AdminSystem/OrderViewer.aspx.cs, ClassLibrary/clsOrder.cs, Skeleton.sln, Testing3/tstOrder.cs
=> somthting is done

ClassLibrary/clsGame.cs, Testing2/tstGame.cs
=> Creating the Find Method For product session (Finished)

AdminSystem/OrderDataEntry.aspx, AdminSystem/OrderDataEntry.aspx.cs, AdminSystem/OrderViewer.aspx.cs, ClassLibrary/clsOrder.cs, Testing3/tstOrder.cs
=> added more testing

AdminSystem/OrderDataEntry.aspx, AdminSystem/OrderDataEntry.aspx.cs, AdminSystem/OrderViewer.aspx.cs, ClassLibrary/clsOrder.cs, Testing3/tstOrder.cs
=> fixed errors

AdminSystem/ProductDataEntry.aspx, ClassLibrary/clsGame.cs, Testing2/tstGame.cs
=> Adding Validation (Middle Layer)(unfinished) product

AdminSystem/CustomerDataEntry.aspx, AdminSystem/CustomerDataEntry.aspx.cs, AdminSystem/OrderDataEntry.aspx, AdminSystem/OrderDataEntry.aspx.cs, ClassLibrary/clsCustomer.cs, Testing4/tstCustomer.cs
=> Added test to Customer

AdminSystem/OrderDataEntry.aspx.cs, ClassLibrary/clsOrder.cs, Testing3/tstOrder.cs
=> added testing

ClassLibrary/clsGame.cs, Testing2/tstGame.cs
=> Adding Validation of release date(product)

AdminSystem/ProductDataEntry.aspx.cs, ClassLibrary/clsGame.cs, Testing2/tstGame.cs
=> Adding Validation (finished middle Layer and Presentation Layer) Product

AdminSystem/OrderDataEntry.aspx.cs, ClassLibrary/clsOrder.cs, Testing3/tstOrder.cs
=> made some changes

AdminSystem/ProductDataEntry.aspx.cs, AdminSystem/ProductList.aspx, AdminSystem/ProductList.aspx.cs, ClassLibrary/ClassLibrary.csproj, ClassLibrary/clsGameCollection.cs, Testing2/TestingProduct.csproj, Testing2/tstGameCollection.cs
- Creating the Collection Class Methods The Add Method (Product)
=> - Creating the Collection Class 

AdminSystem/CustomerDataEntry.aspx, AdminSystem/CustomerDataEntry.aspx.cs, AdminSystem/CustomerViewer.aspx.cs, ClassLibrary/clsCustomer.cs, Testing4/tstCustomer.cs
some test added in customer test
=> some test added in customer test

AdminSystem/ProductDataEntry.aspx.cs, AdminSystem/ProductList.aspx, AdminSystem/ProductList.aspx.cs, ClassLibrary/clsGameCollection.cs, Testing2/tstGameCollection.cs
=> Creating the Collection Class Methods The Edit Method (Product)

AdminSystem/ProductConfirmDelete.aspx, AdminSystem/ProductConfirmDelete.aspx.cs, AdminSystem/ProductDataEntry.aspx.cs, AdminSystem/ProductList.aspx, AdminSystem/ProductList.aspx.cs, ClassLibrary/clsGame.cs, ClassLibrary/clsGameCollection.cs, Testing2/tstGame.cs, Testing2/tstGameCollection.cs
=> Prctical 14b done!!!

AdminSystem/ProductLogin.aspx, AdminSystem/ProductLogin.aspx.cs, ClassLibrary/ClassLibrary.csproj, ClassLibrary/clsGameUser.cs, Testing2/TestingProduct.csproj, Testing2/tstGameCollection.cs, Testing2/tstGameUser.cs
=> Adding a Product Login page

ClassLibrary/clsOrder.cs
=> fixed all the errors

AdminSystem/OrderDataEntry.aspx.cs, Testing3/tstOrder.cs
=> working code

ClassLibrary/clsCustomer.cs
=> gfdxfrxgerror resolved

AdminSystem/OrderDataEntry.aspx.cs, ClassLibrary/clsOrder.cs
=> COMPLETED!!!

AdminSystem/ProductDataEntry.aspx
=> Change product DataEntry Data

AdminSystem/ProductDataEntry.aspx, AdminSystem/ProductDataEntry.aspx.cs
=> Add function on btnCancel in ProductDataEntry page.
